### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by le-s** [le-s/FLEXO#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [ ] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [ ] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

**Comment by ronilbhatia** [comment]
Good job! Your splash page looks really, really nice. A few comments:

![screen shot 2018-12-16 at 12 59 08 pm](https://user-images.githubusercontent.com/32026924/50058803-9cabad00-0132-11e9-8ffe-bcb06a543af1.png)
![screen shot 2018-12-16 at 12 59 09 pm](https://user-images.githubusercontent.com/32026924/50058804-9cabad00-0132-11e9-9186-090bb7a01cd5.png)
1) Their nav bar is a little taller. This then results in all the items in the nav bar being bigger comparatively to yours. The links are also more spread out across the nav bar, so the Turo logo is closer to the left of the screen and the nav-links are closer to the right.
![screen shot 2018-12-16 at 12 59 08 pm](https://user-images.githubusercontent.com/32026924/50058841-10e65080-0133-11e9-90e6-46b0f1087713.png)
![screen shot 2018-12-16 at 12 59 09 pm](https://user-images.githubusercontent.com/32026924/50058842-10e65080-0133-11e9-92ed-90d4d69a2049.png)
2) Modal is small compared to that of Turo's.
3) Input boxes are too small and placeholder text in input boxes is pressed up against the left edge. The placeholder text needs a lot more padding on all sides. Simply adding this extra padding should also result in the input boxes being about the right size, along with increasing the general size of the modal.
4) Sign up button should be bigger and add a space between 'sign' and 'up'.
![screen shot 2018-12-16 at 12 59 08 pm](https://user-images.githubusercontent.com/32026924/50058858-66226200-0133-11e9-8d44-fe89fad14cae.png)
![screen shot 2018-12-16 at 12 59 09 pm](https://user-images.githubusercontent.com/32026924/50058859-66226200-0133-11e9-800b-a9fc228165df.png)
5) Error rendering - I can barely read the error in yours. Also on Turo's actual site the error message is rendered closer to the bottom of the page and has a little symbol with an exclamation mark in a circle. The error message is 'Please check your email and password.' so you should say this instead of 'Invalid Credentials'
6) Demo Login not working
7) The drop down is still kind of messed up it seems to disappear after a second every single time, which is probably because of that `setTimeout` I did. If you open up a question on Monday we could mess with this again.
8) Get rid of the blue outline that appears after you click 'logout' - you can set `outline: none;` on the css for this button and that should get rid of it.
